#############################################################################
# Makefile for building: Elina_Labels
# Generated by qmake (2.01a) (Qt 4.8.7) on: Mon Oct 10 14:29:52 2016
# Project:  Elina_Labels.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Elina_Labels.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = rewrap.cpp \
		mainwindow.cpp \
		ktreport.cpp \
		r3a.cpp \
		production.cpp \
		login.cpp \
		main.cpp \
		elina_labels.cpp \
		mailsender.cpp moc_rewrap.cpp \
		moc_mainwindow.cpp \
		moc_ktreport.cpp \
		moc_r3a.cpp \
		moc_production.cpp \
		moc_login.cpp \
		moc_elina_labels.cpp \
		moc_mailsender.cpp
OBJECTS       = rewrap.o \
		mainwindow.o \
		ktreport.o \
		r3a.o \
		production.o \
		login.o \
		main.o \
		elina_labels.o \
		mailsender.o \
		moc_rewrap.o \
		moc_mainwindow.o \
		moc_ktreport.o \
		moc_r3a.o \
		moc_production.o \
		moc_login.o \
		moc_elina_labels.o \
		moc_mailsender.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Elina_Labels.pro
QMAKE_TARGET  = Elina_Labels
DESTDIR       = 
TARGET        = Elina_Labels

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_rewrap.h ui_mainwindow.h ui_ktreport.h ui_r3a.h ui_production.h ui_login.h ui_elina_labels.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Elina_Labels.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Elina_Labels.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Elina_Labels.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Elina_Labels1.0.0 || $(MKDIR) .tmp/Elina_Labels1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Elina_Labels1.0.0/ && $(COPY_FILE) --parents rewrap.h mainwindow.h ktreport.h r3a.h constants.h production.h login.h elina_labels.h mailsender.h .tmp/Elina_Labels1.0.0/ && $(COPY_FILE) --parents rewrap.cpp mainwindow.cpp ktreport.cpp r3a.cpp production.cpp login.cpp main.cpp elina_labels.cpp mailsender.cpp .tmp/Elina_Labels1.0.0/ && $(COPY_FILE) --parents rewrap.ui mainwindow.ui ktreport.ui r3a.ui production.ui login.ui elina_labels.ui .tmp/Elina_Labels1.0.0/ && (cd `dirname .tmp/Elina_Labels1.0.0` && $(TAR) Elina_Labels1.0.0.tar Elina_Labels1.0.0 && $(COMPRESS) Elina_Labels1.0.0.tar) && $(MOVE) `dirname .tmp/Elina_Labels1.0.0`/Elina_Labels1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Elina_Labels1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_rewrap.cpp moc_mainwindow.cpp moc_ktreport.cpp moc_r3a.cpp moc_production.cpp moc_login.cpp moc_elina_labels.cpp moc_mailsender.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_rewrap.cpp moc_mainwindow.cpp moc_ktreport.cpp moc_r3a.cpp moc_production.cpp moc_login.cpp moc_elina_labels.cpp moc_mailsender.cpp
moc_rewrap.cpp: ui_rewrap.h \
		rewrap.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) rewrap.h -o moc_rewrap.cpp

moc_mainwindow.cpp: ui_mainwindow.h \
		elina_labels.h \
		ui_elina_labels.h \
		mainwindow.h \
		production.h \
		ui_production.h \
		r3a.h \
		ui_r3a.h \
		ktreport.h \
		ui_ktreport.h \
		rewrap.h \
		ui_rewrap.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_ktreport.cpp: ui_ktreport.h \
		ktreport.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ktreport.h -o moc_ktreport.cpp

moc_r3a.cpp: mainwindow.h \
		ui_mainwindow.h \
		elina_labels.h \
		ui_elina_labels.h \
		rewrap.h \
		ui_rewrap.h \
		production.h \
		ui_production.h \
		r3a.h \
		ui_r3a.h \
		ktreport.h \
		ui_ktreport.h \
		r3a.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) r3a.h -o moc_r3a.cpp

moc_production.cpp: ui_production.h \
		production.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) production.h -o moc_production.cpp

moc_login.cpp: ui_login.h \
		mainwindow.h \
		ui_mainwindow.h \
		elina_labels.h \
		ui_elina_labels.h \
		rewrap.h \
		ui_rewrap.h \
		production.h \
		ui_production.h \
		r3a.h \
		ui_r3a.h \
		ktreport.h \
		ui_ktreport.h \
		login.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_elina_labels.cpp: ui_elina_labels.h \
		mainwindow.h \
		ui_mainwindow.h \
		elina_labels.h \
		rewrap.h \
		ui_rewrap.h \
		production.h \
		ui_production.h \
		r3a.h \
		ui_r3a.h \
		ktreport.h \
		ui_ktreport.h \
		elina_labels.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) elina_labels.h -o moc_elina_labels.cpp

moc_mailsender.cpp: mailsender.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mailsender.h -o moc_mailsender.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_rewrap.h ui_mainwindow.h ui_ktreport.h ui_r3a.h ui_production.h ui_login.h ui_elina_labels.h
compiler_uic_clean:
	-$(DEL_FILE) ui_rewrap.h ui_mainwindow.h ui_ktreport.h ui_r3a.h ui_production.h ui_login.h ui_elina_labels.h
ui_rewrap.h: rewrap.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic rewrap.ui -o ui_rewrap.h

ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_ktreport.h: ktreport.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic ktreport.ui -o ui_ktreport.h

ui_r3a.h: r3a.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic r3a.ui -o ui_r3a.h

ui_production.h: production.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic production.ui -o ui_production.h

ui_login.h: login.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic login.ui -o ui_login.h

ui_elina_labels.h: elina_labels.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic elina_labels.ui -o ui_elina_labels.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

rewrap.o: rewrap.cpp rewrap.h \
		ui_rewrap.h \
		elina_labels.h \
		ui_elina_labels.h \
		mainwindow.h \
		ui_mainwindow.h \
		production.h \
		ui_production.h \
		r3a.h \
		ui_r3a.h \
		ktreport.h \
		ui_ktreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rewrap.o rewrap.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		elina_labels.h \
		ui_elina_labels.h \
		rewrap.h \
		ui_rewrap.h \
		production.h \
		ui_production.h \
		r3a.h \
		ui_r3a.h \
		ktreport.h \
		ui_ktreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

ktreport.o: ktreport.cpp ktreport.h \
		ui_ktreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ktreport.o ktreport.cpp

r3a.o: r3a.cpp r3a.h \
		mainwindow.h \
		ui_mainwindow.h \
		elina_labels.h \
		ui_elina_labels.h \
		rewrap.h \
		ui_rewrap.h \
		production.h \
		ui_production.h \
		ktreport.h \
		ui_ktreport.h \
		ui_r3a.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o r3a.o r3a.cpp

production.o: production.cpp production.h \
		ui_production.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o production.o production.cpp

login.o: login.cpp login.h \
		ui_login.h \
		mainwindow.h \
		ui_mainwindow.h \
		elina_labels.h \
		ui_elina_labels.h \
		rewrap.h \
		ui_rewrap.h \
		production.h \
		ui_production.h \
		r3a.h \
		ui_r3a.h \
		ktreport.h \
		ui_ktreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

main.o: main.cpp mainwindow.h \
		ui_mainwindow.h \
		elina_labels.h \
		ui_elina_labels.h \
		rewrap.h \
		ui_rewrap.h \
		production.h \
		ui_production.h \
		r3a.h \
		ui_r3a.h \
		ktreport.h \
		ui_ktreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

elina_labels.o: elina_labels.cpp elina_labels.h \
		ui_elina_labels.h \
		mainwindow.h \
		ui_mainwindow.h \
		production.h \
		ui_production.h \
		r3a.h \
		ui_r3a.h \
		ktreport.h \
		ui_ktreport.h \
		rewrap.h \
		ui_rewrap.h \
		mailsender.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o elina_labels.o elina_labels.cpp

mailsender.o: mailsender.cpp mailsender.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mailsender.o mailsender.cpp

moc_rewrap.o: moc_rewrap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rewrap.o moc_rewrap.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_ktreport.o: moc_ktreport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ktreport.o moc_ktreport.cpp

moc_r3a.o: moc_r3a.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_r3a.o moc_r3a.cpp

moc_production.o: moc_production.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_production.o moc_production.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_elina_labels.o: moc_elina_labels.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_elina_labels.o moc_elina_labels.cpp

moc_mailsender.o: moc_mailsender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mailsender.o moc_mailsender.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

